name: 'Deploy to S3'
description: 'Deploy a static website via aws s3'
inputs:
  bucket:
    description: 'The s3 bucket name'
    required: true
  bucket-region:
    description: 'The region of bucket'
    required: false
    default: 'ap-south-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
outputs:
  website-url:
    description: 'The url of deployed site'
runs:
  using: 'node16'
  main: 'main.js'